# Generated by Django 2.2.4 on 2021-08-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=200)),
                ('altura', models.IntegerField()),
                ('barrio', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('dni', models.CharField(max_length=20)),
                ('obrasocial', models.CharField(max_length=200)),
                ('numero_beneficiario', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Domicilio')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
            },
        ),
    ]
