# Generated by Django 2.2.4 on 2021-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20210808_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='tipos',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Artículo'),
        ),
    ]
