# Generated by Django 2.2.4 on 2021-08-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20210808_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
